import streamlit as st
import pandas as pd
import plotly.express as px
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data_loader import load_alarms, load_tickets, load_predictions

st.title("🔗 Alerts and Tickets Analysis")
st.caption("Understanding what problems are happening and how long they take to fix")
st.divider()

alarms  = load_alarms()
tickets = load_tickets()
preds   = load_predictions()

tickets["open_time"]  = pd.to_datetime(tickets["open_time"])
tickets["close_time"] = pd.to_datetime(tickets["close_time"])

# ── Simple explanation ────────────────────────────────────────
st.info("""
**What is this page about?**
- When a device has a problem → it generates an **Alert**
- When the alert is serious enough → a **Ticket** is created for the team to fix
- This page shows you which problems happen most often and how long fixes take
""")

# ── KPI row ───────────────────────────────────────────────────
total_alarms   = len(alarms)
total_tickets  = len(tickets)
p1_tickets     = (tickets["priority"]=="P1 - Critical").sum()
avg_fix_time   = tickets["resolution_time_hrs"].mean()
open_tickets   = tickets[tickets["status"].isin(["Open","In Progress"])].shape[0]
reopened       = tickets["reopened"].sum()

c1,c2,c3,c4,c5,c6 = st.columns(6)
c1.metric("Total Alerts",         f"{total_alarms:,}",  help="Total alerts generated by all devices")
c2.metric("Total Tickets",        f"{total_tickets:,}", help="Tickets raised from those alerts")
c3.metric("Emergency Tickets",    f"{p1_tickets:,}",    help="P1 Critical tickets — most urgent")
c4.metric("Average Fix Time",     f"{avg_fix_time:.1f}h",help="How long it takes to resolve a ticket")
c5.metric("Still Open",           f"{open_tickets:,}",  help="Tickets not yet resolved")
c6.metric("Reopened Tickets",     f"{reopened:,}",       help="Tickets that were closed but had to be reopened")

st.divider()

# ── Most common problems ───────────────────────────────────────
st.subheader("🔥 What Problems Happen Most Often?")
st.caption("These are the most common alert types. Fixing the root cause of the top ones will reduce your workload significantly.")

event_map = {
    "LinkDown":         "🌐 Network Link Failure",
    "HighCPU":          "💻 High CPU Usage",
    "HighMemory":       "🧠 High Memory Usage",
    "DiskFull":         "💾 Disk Full",
    "PacketLoss":       "📡 Network Packet Loss",
    "LatencySpike":     "⏱️ Slow Response Time",
    "AuthFailure":      "🔐 Failed Login Attempt",
    "HardwareError":    "⚙️ Hardware Problem",
    "ConfigChange":     "🔧 Configuration Change",
    "ReachabilityLost": "❌ Device Unreachable",
}
alarms["Alert Type"] = alarms["event_type"].map(event_map).fillna(alarms["event_type"])
event_counts = alarms["Alert Type"].value_counts().reset_index()
event_counts.columns = ["Alert Type","Count"]

fig = px.bar(
    event_counts, x="Count", y="Alert Type",
    orientation="h",
    color_discrete_sequence=["#E24B4A"],
    height=380, text="Count",
    labels={"Alert Type":"Problem Type","Count":"How Many Times"}
)
fig.update_traces(textposition="outside")
fig.update_layout(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="rgba(0,0,0,0)",
    margin=dict(t=10,b=10,l=0,r=0),
    xaxis_title="How Many Times This Happened",
    yaxis_title=""
)
st.plotly_chart(fig, use_container_width=True)
st.caption("💡 Focus on fixing the root cause of the top 3 problems — this will reduce 60-70% of all alerts")
st.divider()

# ── Ticket urgency and fix time ───────────────────────────────
st.subheader("⏱️ How Urgent Are the Tickets and How Long to Fix?")
col_a, col_b = st.columns(2)

with col_a:
    st.caption("Ticket urgency breakdown")
    pri_counts = tickets["priority"].value_counts().reset_index()
    pri_counts.columns = ["Priority","Count"]
    pri_counts["Priority"] = pri_counts["Priority"].map({
        "P1 - Critical": "🔴 P1 Emergency",
        "P2 - High":     "🟠 P2 Urgent",
        "P3 - Medium":   "🟡 P3 Normal",
        "P4 - Low":      "🟢 P4 Low",
    })
    fig2 = px.pie(
        pri_counts, values="Count", names="Priority",
        hole=0.5, height=300,
        color="Priority",
        color_discrete_map={
            "🔴 P1 Emergency":"#E24B4A",
            "🟠 P2 Urgent":   "#EF9F27",
            "🟡 P3 Normal":   "#639922",
            "🟢 P4 Low":      "#378ADD",
        }
    )
    fig2.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        margin=dict(t=10,b=10,l=0,r=0)
    )
    st.plotly_chart(fig2, use_container_width=True)

with col_b:
    st.caption("Average hours to fix by urgency level")
    fix_time = tickets.groupby("priority")["resolution_time_hrs"].mean().reset_index()
    fix_time.columns = ["Priority","Avg Hours to Fix"]
    fix_time["Priority"] = fix_time["Priority"].map({
        "P1 - Critical": "🔴 P1 Emergency",
        "P2 - High":     "🟠 P2 Urgent",
        "P3 - Medium":   "🟡 P3 Normal",
        "P4 - Low":      "🟢 P4 Low",
    })
    fix_time["Avg Hours to Fix"] = fix_time["Avg Hours to Fix"].round(1)
    fig3 = px.bar(
        fix_time, x="Priority", y="Avg Hours to Fix",
        color_discrete_sequence=["#378ADD"],
        height=280, text="Avg Hours to Fix"
    )
    fig3.update_traces(textposition="outside")
    fig3.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        margin=dict(t=10,b=10,l=0,r=0),
        xaxis_title="", yaxis_title="Hours to Fix"
    )
    st.plotly_chart(fig3, use_container_width=True)
    st.caption("💡 P1 tickets should be fixed within 8 hours. Longer times indicate staffing or skill gaps.")

st.divider()

# ── All devices with open tickets ─────────────────────────────
st.subheader("📋 All Devices with Open Tickets")
st.caption("Every device that currently has an unresolved ticket — sorted by number of open tickets")

open_t = tickets[tickets["status"].isin(["Open","In Progress"])]
all_devices = (
    open_t.groupby("asset_id")
    .agg(
        Open_Tickets=("ticket_id","count"),
        Avg_Fix_Hours=("resolution_time_hrs","mean")
    )
    .reset_index()
    .sort_values("Open_Tickets", ascending=False)
)
all_devices = all_devices.merge(
    preds[["asset_id","risk_level","recommended_action","criticality"]],
    on="asset_id", how="left"
)
all_devices["Risk Status"] = all_devices["risk_level"].map({
    "CRITICAL": "🟣 Emergency",
    "HIGH":     "🔴 Urgent",
    "MEDIUM":   "🟡 Monitor",
    "LOW":      "🟢 Healthy"
})
all_devices["Avg_Fix_Hours"] = all_devices["Avg_Fix_Hours"].round(1)
all_devices = all_devices[[
    "asset_id","criticality","Open_Tickets",
    "Avg_Fix_Hours","Risk Status","recommended_action"
]]
all_devices.columns = [
    "Device ID","Importance","Open Tickets",
    "Avg Fix Time (hrs)","Risk Status","What To Do"
]

st.caption(f"Total: {len(all_devices):,} devices with open tickets")
st.dataframe(all_devices, use_container_width=True, hide_index=True, height=500)
